### PR TITLE
Make brace openings similar to Unity coding standards

### PR DESCRIPTION
**Pull request by devmcclu**
### What is this?
All snippets have had their opening braces moved to the next line.

### Why was this done?
Unity, as well as C# itself, has a standard convention for braces. This is mentioned [here](https://github.com/a-patel/csharp-style-guide#brace-style) in this C# style guide, which is relevant to Unity as well. Most of Microsoft's documentation also follows this standard, as seen [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions).

### CODE REVIEW

**Comment by trevorjmcdonald** [comment]
Definitely this, I actually found this looking to see if this was configurable. Standard C# convention is opening bracket on newline. I'd also be fine with it being configurable if nothing else.

**Comment by edwonia** [comment]
I wish this was configurable as well, also putting "private" before method names by default is annoying, I usually leave that out.

For now, how do I get this working from the commit referenced?

**Comment by Cdddo** [comment]
While I also prefer the Unity coding standards with the bracket in a new line, I think it should be optional.

**Comment by kleber-swf** [comment]
Hello.

Unfortunatelly I can't mege this commit since it changes everything to Allman style, which is great and all, but I can't enforce it with 600k+ people already using the extension with the K&R style.

I'm considering making it an option. It will change everything (since it's only a collection of snippets not an "real" extension per se) but I can give it a try this holidays.

Thanks for the feedback.

**Comment by Cdddo** [comment]
For anyone interested, I'm committed to maintaining a version with the new line standard at
https://github.com/Cdddo/vscode-unity-code-snippets

**Review by equintee — COMMENTED** [review]
Most Unity developers use VScode so it makes my code incomprehensible across the team.

This solution works fine for me.

**Comment by kleber-swf** [comment]
Version 2.0.0 now has the option to change the indentation style to Allman or K&R.
I hope it's not too late :sweat_smile:

**Pull request closed without merging**
